from .test_basicViews import *
from .test_reportExtraViews import *
from .test_assessViews import *
from .test_aacAdminViews import *
from .test_gradingViews import *
from .test_rubricViews import *
from .test_dataCollection import *
from .test_DecActsViews import *
from .test_APIs import *
from .test_graphingCSV import *
from .test_mixins import *
from .test_signals import *
from .forms.test_adminforms import *
from .forms.test_gradingforms import *
from .forms.test_assessmentforms import *
from .forms.test_datacollectionforms import *
from .forms.test_otherforms import *
from .forms.test_sloforms import *