# Generated by Django 2.2.5 on 2019-12-03 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0001_squashed_0058_auto_20191202_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsupplement',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dataadditionalinformation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Report'),
        ),
        migrations.AlterField(
            model_name='decisionsactions',
            name='sloIR',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='makeReports.SLOInReport'),
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sloinreport',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='slostatus',
            name='sloIR',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='makeReports.SLOInReport'),
        ),
    ]
