# Generated by Django 3.0.4 on 2020-03-15 23:46

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0004_auto_20191213_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsupplement',
            name='supplement',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='asssements/supplements'),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='frequencyChoice',
            field=models.CharField(choices=[('S', 'Once/semester'), ('Y', 'Once/year'), ('O', 'Other')], default='O', max_length=100, verbose_name='frequency choice'),
        ),
        migrations.AlterField(
            model_name='dataadditionalinformation',
            name='supplement',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='data/supplements'),
        ),
        migrations.AlterField(
            model_name='reportsupplement',
            name='supplement',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='data/supplements'),
        ),
        migrations.AlterField(
            model_name='slo',
            name='blooms',
            field=models.CharField(choices=[('', '------'), ('KN', 'Knowledge'), ('CO', 'Comprehension'), ('AP', 'Application'), ('AN', 'Analysis'), ('SN', 'Synthesis'), ('EV', 'Evaluation')], max_length=50, verbose_name="Bloom's taxonomy level"),
        ),
    ]
