# Generated by Django 3.0.4 on 2020-03-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0005_auto_20200315_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredFieldSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Setting', max_length=200)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
    ]
