# Generated by Django 3.0.7 on 2020-11-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0006_requiredfieldsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeprogram',
            name='accredited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='accredited',
            field=models.BooleanField(default=False),
        ),
    ]
